# Generated by Django 3.2.8 on 2021-10-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128)),
                ('autor', models.CharField(max_length=64)),
                ('co_autor', models.CharField(max_length=64)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('emprestado', models.BooleanField(default=False)),
                ('quantidade', models.PositiveIntegerField()),
                ('partimonio', models.CharField(max_length=32)),
                ('ativo', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'db_table': 'Tabela do Livro',
            },
        ),
    ]
