# Generated by Django 3.2.8 on 2021-11-02 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0003_livros_editora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.AddField(
            model_name='livros',
            name='categoria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='livro.catagoria'),
        ),
    ]
