# Generated by Django 3.2.8 on 2021-11-02 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('livro', '0005_rename_catagoria_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='usuarios',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuarios'),
            preserve_default=False,
        ),
    ]
