# Generated by Django 3.2.8 on 2021-10-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_alter_livros_co_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='editora',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
