# Generated by Django 3.2.8 on 2021-11-02 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0004_auto_20211102_1951'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagoria',
            new_name='Categoria',
        ),
    ]
