# Generated by Django 3.2.8 on 2021-11-05 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('livro', '0008_categoria_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuarios'),
        ),
    ]
