# Generated by Django 3.2.9 on 2021-11-26 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0011_alter_emprestimos_nome_emprestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descricao',
            field=models.CharField(max_length=128),
        ),
    ]
